name: Daily Scheduled Build

on:
  schedule:
    - cron: '0 0 * * *'  # Midnight UTC
#    - cron: '*/5 * * * *'  # Every 5 minutes (for testing purposes)

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log success message
        run: echo "Scheduled build completed successfully!"
